### ISSUE TITLE
Add accessers to the system clipboard.

### ISSUE THREAD

**Issue by MakoEnergy** [BlackToppStudios/Mezzanine#106]
At a minimum we should be able to retrieve a string (if one is present) from the clip board to be pasted/injected into the UI system.  Additionally it would be nice to be able to write to the system clipboard.

**Comment by trgrote** [comment]
SDL exposes this API for cross platform clipboard access
https://wiki.libsdl.org/SDL_GetClipboardText
https://wiki.libsdl.org/SDL_SetClipboardText

**Comment by Sqeaky** [comment]
char* SDL_GetClipboardText(void)

Damn, that looks easy.

Thanks for letting us know.

**Comment by Sqeaky** [comment]
I wonder how or if this handles rich text, images and other non text stuff.

**Comment by MakoEnergy** [comment]
I looked it over, I didn't see anything obvious.  Then I looked at Qt, following the rabbit hole down.  Qt has a harder to follow but also more feature rich clipboard that has a simple API for all those things.  I also looked into how to implement it ourselves and at first glance it seems to need to be aware of the window manager used from the OS.  

So I don't know which would be the ideal solution here.  I'd like more than just text, but honestly text will suit 95% of all our needs.  If possible, I'd also like to not deepen our dependence on SDL, but if it really does need the window manager...well SDL is already handling that so we wouldn't be all that much worse off.

**Comment by Sqeaky** [comment]
I think SDL is a perfectly reasonable choice for right this second even if it cannot handle rich copypasta. This is really the most mild kind of deepening of that whole. Aren't we still getting input from SDL?

**Comment by MakoEnergy** [comment]
Yes.  Input/app events are the only things SDL is doing at the moment.  Chances are when we go to Ogre 2.0+ we'll be forced into using it for full blown window management as well.  Reason being that the Ogre windowing code has some known bugs but no one wants to touch it.  

And yes, this is fairly mild.  But if making our own implementation is also mild, then maybe we can do that.  But at first glance it seems it may not be.  If that's the case then using SDL would be our best bet.

**Comment by trgrote** [comment]
If using SDL's API for this is fine, for now, then I can grab this low hanging fruit and implement it.

My only question would be where to put it? I was thinking two functions in the Input namespace, or maybe as methods in InputManager.

**Comment by MakoEnergy** [comment]
I think I'd rather see them as free functions in the input namespace.  We have a pattern that exists for other namespaces (such as Graphics and Resource) where we have a file named [Namespace]utilities.h/.cpp and we put stuff like this into that.  Currently Input lacks a file like this but that makes the most sense to me.  This means creating inpututilities.h and inpututilities.cpp in the input folder.

**Comment by trgrote** [comment]
Alright.  I'll go write that up. Shouldn't take too long.
