### ISSUE TITLE
Texture packing algorithm

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezzanine#108]
For both text and bitmap fonts we need a way to automatically generate texture and font atlas's. There are algorithms that solve this they need need to be implemented in a way that makes sense in our code.

**Comment by MakoEnergy** [comment]
We are still lacking font capability, however generic texture packing was added with the Proposed-TexturePacker branch merger some time ago.  
https://github.com/BlackToppStudios/Mezzanine/commit/4c21197941ee3643fd01bd7d7a422031ecc27ea8
