### ISSUE TITLE
Re-Design Event manager

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezzanine#18]
The event manager is based on an old design. It was intended to be a queue for game, OS and maybe other events. It should only handle user input and maybe windowing events from the OS. 

Its API needs to be simplified and it needs to support all available UI input methods.

It was defined to handle a simpler single threaded event model. Likely a publisher/subscriber model based around a number threadsafe lockless queues with a strong data sharing model would be suitable.

**Comment by MakoEnergy** [comment]
This has been resolved recently.  The old event system gutted in favor of a more flexible system.
