### ISSUE TITLE
Timing Tests Failing on windows Vista.

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezzanine#56]
Some of the tests are failing, below is a list of of tests and possible explanations from the mailing list. The need to be investigated and at a minimum failures turned into warnings.

**Warnings**
 Why Sqeaky thinks these are warnings instead of failures.
_BinaryTools::DecodeTime_ - Just isn't as fast as the olther
algorithm in debug mode, if this is release, then there is a problem.

_DAGPerformance::TimingVariance0.1%_ - Not every platform provides an
accurate enough timer to pass this test. The DAGScheduler pause
timing, what this test ultimately measures, is based on a rolling
level of correction based on the inaccuracy of predications from
earlier frames, but it can't be much more accurate than the resolution
of provided high performance timer. On XP the timer provides
resolutions between 1500 and 5000 microseconds, just not very good.
You could add "DAGPerformance debugtests" to your IDEs arguments and
drop breakpoints in DAGPerformancetest.h to see how this works if you
want.

_Resource::ArgIsFastest_ - haven't performance tested this on windows
yet, it could be that string manipulation in debug is slow or that
syscalls in window are slow, I am betting on the former

**Failures**
_LogTool::EndDuration_ - This is another test that uses a timer to
test duration accuracies, I bet this is suffering from the same issues
as the earlier timing variance test and you could check by debugging
"LogTool debugtests" and putting breakpoints in logtooltests.h(line
102). if the timer is just too inaccurate, then either the timing
could be loosen from 9900-12000 to something like 8000-14000 to
accommodate all but the worst system timers. If the timer is too bad
for that  the TEST_WARN macro could be used instead TEST. That is a
judge ment call for someone who can debug the issue and see what is
going on in there.

**Comment by MakoEnergy** [comment]
While the Mezzanine Engine can theoretically be built on Windows Vista, because we haven't consciously made any choices that would exclude it, we aren't explicitly testing it anywhere.  Nor do we plan to start.  This makes Windows Vista irrelevant for issues.  Closing.
