### ISSUE TITLE
Remove unmanaged raw pointer returns from API

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezzanine#60]
Some items, like the Resource manager and the EventManager return raw pointers that the game developer must manually clean up. Pointers that are only handles and needn't be cleaned up by the game developer are fine (for now).

These should be replaced by some kind of smart pointer being returned. For now we must assume C++11 is not available, so countedptr should be used and perhaps an analog for unique_ptr could be created.

**Comment by MakoEnergy** [comment]
A lot of little work was done initially, and right now it's hard to say any of these issues still remain.  If they do they'll be caught by peer review when we port them to Jagati repos.  Without explicit examples to fix going forward I'm closing this issue.
