### ISSUE TITLE
Fix Exception error message handling.

### ISSUE THREAD

**Issue by MakoEnergy** [BlackToppStudios/Mezzanine#88]
Currently, all exceptions are being logged inevitably through the Threading system which has it's logs aggregated each frame (presumably flushed each frame as well).  When an exception is thrown the application shuts down before this can happen, resulting in exception messages not being logged to log files.

Logging should be fixed such that the exception message makes it to the log file.

**Comment by Sqeaky** [comment]
This one might be fixed, we need to check the unit tests.
